### ISSUE TITLE
[review] 一些建议

### ISSUE THREAD

**Issue by mritd** [YahuiAn/Go-bjut#4]
### config 配置文件加入 gitignore

测试短信模板是无效的，但是看相关密码等可能暴露一些隐私信息，最好完全移除项目的所有 commit 并重新提交，防止搜索引擎索引

### sms api 调用参数错误

代码 https://github.com/YahuiAn/Go-bjut/blob/be5b6a472377c9e98205ee8cb56f3132ca59aaa7/service/card/message.go#L50 处 rand 一个 int 然后强转 string，这个 int 会被当作 byte 字节这种对应到字符，大部份时候它是个乱码，**此参数应该是个随机字符串，并且有一定长度**

### 代码中大量调用 viper 库获取配置

viper 库配置文件在以前是无法并发读取的，现在有没有坑不清楚，参考 issue https://github.com/spf13/viper/issues/482

### 错误处理问题

很多地方错误处理不正确，譬如 https://github.com/YahuiAn/Go-bjut/blob/be5b6a472377c9e98205ee8cb56f3132ca59aaa7/service/card/message.go#L92 http 实际返回的错误 json 串是无法反序列化到你的结构体的，所以会造成错误信息丢失，出现问题无法排查

### log 处理

推荐你直接使用 logrus 库，而不是造轮子

### 关键性 配置抽离

针对 sms 抽象合理接口，腾讯云的送达率并不 ok，或者说国内的送达率可能在某一段时间你会切换 sms 提供商，譬如阿里大鱼；而且通知未来可能扩充到 邮件、微信... 

其他的太晚了，懒得看了....

**Comment by YahuiAn** [comment]
@mritd 
1. 因为目前项目还有好多功能都没做，所以暂时保留了配置文件，后期会加入gitignore。card_sms配置中的信息都是假的，所以隐私不用担心，嘿嘿~
2. 哇，这个bug简直了，真是服了我自己，我打算修改为下面这样。
```go
func main() {
	rand.Seed(time.Now().Unix())
	random := strconv.Itoa(rand.Int())[0:5]
	fmt.Println(random)
}
```
3. 之前有多人推荐用viper，然后我调研了一圈，感觉viper还可以，就用了它。因为目前项目还没上线，所以我打算等上线后再看看有没有什么坑吧。
4. 这个Unmarshal函数没有做错误处理确实是偷懒了，最近我也在看go语言中错误处理的最佳实践，总感觉对错误处理做的不太好，不是过多处理，就是疏忽了某些错误。
5. 是的，不应该盲目的造轮子，只是我这个logger当时需求挺简单的，就参考了一些文章，写了一个简单的。后面项目上线了，对日志的需求变复杂了，我会换掉自己的这个日志。
6. 目前只做了短信通知，后期会考虑做小程序，邮件等通信，等通知类型多了，再考虑抽象合理的接口，因为我目前写的业务系统还不太多，所以对面向接口编程的感悟还不是很深。
最后，谢谢帮我review代码😁

**Comment by mritd** [comment]
凑巧 github 推荐我的，就看了一下...然后以为是 sms 信息泄漏，测试了一下
